## BLAST parameters
BLAST_BINARY = 'data/ncbi-blast-2.3.0+/bin'
BLAST_DATABASE = 'data/16SMicrobial/16SMicrobial'
BLAST_CUTOFF_SCORE = 100
BLAST_CUTOFF_PERCENT = 10
BLAST_COVERAGE = 95
BLAST_PERCENTAGE_IDENTITY = 95

## MSA parameters
HIT_SEQUENCE_BPS = 10
MUSCLE_BINARY = '/usr/bin/muscle'

## Scores
ALIGNMENT_GAP = -2.5
ALIGNMENT_MISMATCH = -2
ALIGNMENT_MATCH = 1

## Bootstrap
BOOTSTRAP = 100


